---
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    # there is no reason to test external files
    - "vendor/**/*"
    - "node_modules/"
  DisplayCopNames: true
  ExtraDetails: true
  DisplayStyleGuide: true
  AllowSymlinksInCacheRootDirectory: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/BlockLength:
  Exclude: []
  ExcludedMethods:
    - describe
    - context
    - shared_examples

Metrics/LineLength:
  Exclude:
    - "Gemfile"
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
    - git
    - ftp
  IgnoreCopDirectives: true
