---
language: ruby

before_install:
  - yes | gem update --system --force
  - gem install bundler
  - npm install
script:
  - node node_modules/markdownlint-cli/markdownlint.js .
  - bundle install --jobs=3 --retry=3
  - bundle exec jekyll build
