---
language: ruby

before_install:

  # XXX use bundler 1.x for now because OpenBSD does not have bundler 2.x in
  # the package tree.
  # - yes | gem update --system --force
  # - gem install bundler
  - npm install
  - pip install --user yamllint
  - bundle install --jobs=3 --retry=3
script:
  - node node_modules/markdownlint-cli/markdownlint.js .
  - yamllint -c .yamllint.yml -s .
  - bundle exec jekyll build
  # test links, but ignore "linking to internal hash # that does not exist"
  # error. disable external tests to process tests faster.
  - bundle exec htmlproofer --url-ignore "/^#$/" --disable-external _site/
