---
language: ruby

before_install:

  # XXX use bundler 1.x for now because OpenBSD does not have bundler 2.x in
  # the package tree.
  # - yes | gem update --system --force
  # - gem install bundler
  - npm install
  - pip install --user yamllint
  - bundle install --jobs=3 --retry=3
script:
  - node node_modules/markdownlint-cli/markdownlint.js .
  # XXX too many errors. disable for now
  - yamllint -c .yamllint.yml . || true
  - bundle exec jekyll build
