require "rqrcode"


task default: %w[qr_code_svg]

desc "Create QR code for the URL of the site"
task :qr_code_svg do
  puts "Generating QR code for the site URL"
  qrcode = RQRCode::QRCode.new("http://info.mkrsgh.org")
  File.open("info.mkrsgh.org.svg", "w") do |f|
    f.write qrcode.as_svg
  end
end
