require "rqrcode"

urls = [
  "http://info.mkrsgh.org",
  "http://info.mkrsgh.org/hotel",
  "http://info.mkrsgh.org/makerspace"
]

def qrcode_url(url)
  RQRCode::QRCode.new(url)
end

task default: urls

urls.each do |url|
  desc "Generate QR Code for #{url}"
  task url do
    File.open("#{url.gsub(%r{[/]}, '-')}.qrcode.svg", "w") do |f|
      f.write qrcode_url(url).as_svg
    end
  end
end
