---

name: aspell
on:
  push: null

jobs:
  aspell:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - 2.6
    name: Check spellings in markdown files
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Cache bundler files
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install ruby version ${{ matrix.ruby }}
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install bundler and gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install aspell
        run: |
          sudo apt-get install aspell aspell-en
          aspell --version

      - name: Show aspel version
        run: |
          aspell --version
      - name: Run aspel
        run: |
          bundle exec rake aspell
