---
name: Deploy jekyll site to S3
on:
  push:
    branches:
      - devel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Cache bundler files
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Install bundler
        run: gem install bundler
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Build static site
        run: env JEKYLL_ENV=production bundle exec jekyll build --config _config.yml

      - name: Build the site again to generate resized images
        # see https://github.com/wildlyinaccurate/jekyll-responsive-image/issues/94
        run: env JEKYLL_ENV=production bundle exec jekyll build --config _config.yml

      - name: Gzip files
        run: |
          find _site/ -iname "*.html" -exec gzip -9 -n {} \; -exec mv {}.gz {} \;
          find _site/ -iname "*.js"   -exec gzip -9 -n {} \; -exec mv {}.gz {} \;
          find _site/ -iname "*.css"  -exec gzip -9 -n {} \; -exec mv {}.gz {} \;
          find _site/ -iname "*.svg"  -exec gzip -9 -n {} \; -exec mv {}.gz {} \;

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*.html" --exclude "*.js" --exclude "*.css" --exclude "*.svg" --exclude "assets/img/*"

          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*" --include "*.html" --content-encoding "gzip" --cache-control "public"
          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*" --include "*.js"   --content-encoding "gzip" --cache-control "public, max-age=864000, s-maxage=864000"
          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*" --include "*.css"  --content-encoding "gzip" --cache-control "public, max-age=864000, s-maxage=864000"
          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*" --include "*.svg"  --content-encoding "gzip" --cache-control "public, max-age=864000, s-maxage=864000"

          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME }} --delete --exclude "*" --include "assets/img/*" --cache-control "public, max-age=864000, s-maxage=864000"
