---
name: Release a tagged commit

# run this workflow when tagged with 'v*', such as 'v1.0.0'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Cache bundler files
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies & build site
        uses: limjh16/jekyll-action-ts@v2

      - name: Create release asset file
        run: tar -C _site -cvzf site.tar.gz .

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload the asset file
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # This pulls from the CREATE RELEASE step above, referencing it's ID
          # to get its outputs object, which include a `upload_url`. See this
          # blog post for more info:
          # https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./site.tar.gz
          asset_name: site.tar.gz
          asset_content_type: application/tar+gzip
